# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaf18a37c28b4a73806bc8b215db266dc493a92a596c41947c3cad9905c86b02b63ded72038172ddc78aabd09a5146a62d7ee5930b6d8cfb27a649f398f8e71d

test:
  secret_key_base: 21d7ae2437d077f5d62ccbd4f3a614c52453a7037346d7cdf5125ceb08d89f89fabd467688309b6e79b2f2fed4dc364fe90ae4ead1cc6b17456c7629e58d33be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
